version: "2"

services:
  califit-be:
    image: hieuphq/califit-be:latest
    environment:
      #- VIRTUAL_PROTO=http
      #- HTTPS_METHOD=redirect
      #- HTTPS_METHOD=nohttp
      - VIRTUAL_HOST=cali.kalimtab.com
      #- LETSENCRYPT_HOST=presta.kalimtab.com
      #- LETSENCRYPT_EMAIL=hieupq@dwarvesv.com
    expose:
      - 80
  califit-db:
    image: "postgres:9.6"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: califit
    container_name: califit-be_db
    ports:
      - "5432:5432"
    expose:
      - 5432
networks:
  default:
    external:
      name: nginx-proxy
