basePath: /api/
consumes:
- application/json
definitions:
  Cities:
    description: A list of City (default view)
    example:
      data:
      - city_id: Et praesentium.
        city_name: Quas reiciendis eum natus rerum sit accusantium.
        created_at: "1993-07-17T01:28:42Z"
      paginate:
        current_page: 3.161111681195654e+16
        total_item: 4.2427972326251945e+18
        total_page: 3.2758635658199117e+18
    properties:
      data:
        example:
        - city_id: Et praesentium.
          city_name: Quas reiciendis eum natus rerum sit accusantium.
          created_at: "1993-07-17T01:28:42Z"
        items:
          $ref: '#/definitions/CityGeneral'
        type: array
      paginate:
        $ref: '#/definitions/Paginate'
    title: 'Mediatype identifier: application/vnd.cities+json; view=default'
    type: object
  City:
    description: a city detail (default view)
    example:
      city_id: Illum voluptatibus tenetur numquam eum.
      city_name: Est aut ducimus ducimus repellat minus.
      created_at: "1977-11-30T13:57:32Z"
    properties:
      city_id:
        example: Illum voluptatibus tenetur numquam eum.
        type: string
      city_name:
        example: Est aut ducimus ducimus repellat minus.
        type: string
      created_at:
        example: "1977-11-30T13:57:32Z"
        format: date-time
        type: string
    title: 'Mediatype identifier: application/vnd.city+json; view=default'
    type: object
  CityGeneral:
    description: a city detail (general view)
    example:
      city_id: Et praesentium.
      city_name: Quas reiciendis eum natus rerum sit accusantium.
      created_at: "1993-07-17T01:28:42Z"
    properties:
      city_id:
        example: Et praesentium.
        type: string
      city_name:
        example: Quas reiciendis eum natus rerum sit accusantium.
        type: string
      created_at:
        example: "1993-07-17T01:28:42Z"
        format: date-time
        type: string
    title: 'Mediatype identifier: application/vnd.city+json; view=general'
    type: object
  Login_response:
    description: Login response (default view)
    example:
      token: Non ipsa et quam dolore.
      user_info:
        company_address: Sint qui sed dolor.
        company_name: Inventore perferendis molestiae vitae repellendus.
        contact_name: A quo quo officiis rerum qui amet.
        email: Assumenda voluptatum quos.
        phone: Accusantium hic vel.
    properties:
      token:
        example: Non ipsa et quam dolore.
        type: string
      user_info:
        $ref: '#/definitions/User_info'
    title: 'Mediatype identifier: application/vnd.login_response+json; view=default'
    type: object
  LoginPayload:
    example:
      email: jamesbond@gmail.com
      password: abcd1234
    properties:
      email:
        example: jamesbond@gmail.com
        format: email
        maxLength: 400
        minLength: 6
        type: string
      password:
        example: abcd1234
        maxLength: 100
        minLength: 8
        type: string
    required:
    - email
    - password
    title: LoginPayload
    type: object
  Paginate:
    description: pagination of a resources (default view)
    example:
      current_page: 3.161111681195654e+16
      total_item: 4.2427972326251945e+18
      total_page: 3.2758635658199117e+18
    properties:
      current_page:
        example: 3.161111681195654e+16
        format: int64
        type: integer
      total_item:
        example: 4.2427972326251945e+18
        format: int64
        type: integer
      total_page:
        example: 3.2758635658199117e+18
        format: int64
        type: integer
    title: 'Mediatype identifier: application/vnd.paginate+json; view=default'
    type: object
  RegisterPayload:
    example:
      company_address: 445 Mount Eden Road, Mount Eden, Auckland
      company_name: Express company
      contact_name: Doe
      email: jamesbond@gmail.com
      password: abcd1234
      phone: p0lba0qgou
    properties:
      company_address:
        example: 445 Mount Eden Road, Mount Eden, Auckland
        maxLength: 500
        minLength: 1
        type: string
      company_name:
        example: Express company
        maxLength: 500
        minLength: 1
        type: string
      contact_name:
        example: Doe
        maxLength: 200
        minLength: 1
        type: string
      email:
        example: jamesbond@gmail.com
        format: email
        maxLength: 150
        minLength: 6
        type: string
      password:
        example: abcd1234
        maxLength: 100
        minLength: 8
        type: string
      phone:
        example: p0lba0qgou
        maxLength: 50
        type: string
    required:
    - email
    - password
    - contact_name
    - phone
    - company_address
    - company_name
    title: RegisterPayload
    type: object
  Token:
    description: A token (default view)
    example:
      token: Atque reiciendis saepe voluptatem rerum et voluptatum.
    properties:
      token:
        description: A JWT token
        example: Atque reiciendis saepe voluptatem rerum et voluptatum.
        type: string
    title: 'Mediatype identifier: application/vnd.token+json; view=default'
    type: object
  User_info:
    description: User info (default view)
    example:
      company_address: Sint qui sed dolor.
      company_name: Inventore perferendis molestiae vitae repellendus.
      contact_name: A quo quo officiis rerum qui amet.
      email: Assumenda voluptatum quos.
      phone: Accusantium hic vel.
    properties:
      company_address:
        example: Sint qui sed dolor.
        type: string
      company_name:
        example: Inventore perferendis molestiae vitae repellendus.
        type: string
      contact_name:
        example: A quo quo officiis rerum qui amet.
        type: string
      email:
        example: Assumenda voluptatum quos.
        type: string
      phone:
        example: Accusantium hic vel.
        type: string
    title: 'Mediatype identifier: application/vnd.user_info+json; view=default'
    type: object
  error:
    description: Error response media type (default view)
    example:
      code: invalid_value
      detail: Value of ID must be an integer
      id: 3F1FKVRR
      meta:
        timestamp: 1.458609066e+09
      status: "400"
    properties:
      code:
        description: an application-specific error code, expressed as a string value.
        example: invalid_value
        type: string
      detail:
        description: a human-readable explanation specific to this occurrence of the
          problem.
        example: Value of ID must be an integer
        type: string
      id:
        description: a unique identifier for this particular occurrence of the problem.
        example: 3F1FKVRR
        type: string
      meta:
        additionalProperties: true
        description: a meta object containing non-standard meta-information about
          the error.
        example:
          timestamp: 1.458609066e+09
        type: object
      status:
        description: the HTTP status code applicable to this problem, expressed as
          a string value.
        example: "400"
        type: string
    title: 'Mediatype identifier: application/vnd.goa.error; view=default'
    type: object
host: califit-be.club
info:
  contact:
    email: hieu.phq@gmail.com
    name: Hieu Phan
  description: An API for califit-be
  title: The califit-be Backend API
  version: ""
paths:
  auth/login:
    post:
      description: Sign a company user in
      operationId: authentication#login
      parameters:
      - in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/LoginPayload'
      produces:
      - application/vnd.goa.error
      - application/vnd.login_response+json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/Login_response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/error'
        "500":
          description: Internal Server Error
      schemes:
      - https
      summary: login authentication
      tags:
      - authentication
  auth/logout:
    post:
      description: Sign a company user in
      operationId: authentication#logout
      parameters:
      - in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/LoginPayload'
      produces:
      - application/vnd.goa.error
      - application/vnd.login_response+json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/Login_response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/error'
        "500":
          description: Internal Server Error
      schemes:
      - https
      summary: logout authentication
      tags:
      - authentication
  auth/register:
    post:
      description: Create a new user
      operationId: authentication#register
      parameters:
      - in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/RegisterPayload'
      produces:
      - application/vnd.goa.error
      - application/vnd.token+json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/Token'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/error'
        "500":
          description: Internal Server Error
      schemes:
      - https
      summary: register authentication
      tags:
      - authentication
  city:
    get:
      description: List cities
      operationId: city#list
      parameters:
      - default: 10
        description: limit for paginate
        in: query
        name: limit
        required: false
        type: integer
      - default: ""
        description: query for find cities by name
        in: query
        name: name
        required: false
        type: string
      - default: 0
        description: offset for paginate
        in: query
        name: offset
        required: false
        type: integer
      produces:
      - application/vnd.cities+json
      - application/vnd.goa.error
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/Cities'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/error'
      schemes:
      - https
      summary: list city
      tags:
      - city
  city/{cityID}:
    get:
      description: Get a city by ID
      operationId: city#show
      parameters:
      - description: City ID
        in: path
        name: cityID
        required: true
        type: string
      produces:
      - application/vnd.city+json
      - application/vnd.goa.error
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/City'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/error'
      schemes:
      - https
      summary: show city
      tags:
      - city
produces:
- application/json
responses:
  InternalServerError:
    description: Internal Server Error
schemes:
- https
securityDefinitions:
  jwt:
    description: |-
      Use JWT to authenticate

      **Security Scopes**:
        * `api:access`: API access
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
