// Code generated by goagen v1.4.0, DO NOT EDIT.
//
// API "califit-be Backend API": Application Resource Href Factories
//
// Command:
// $ goagen
// --design=github.com/hieuphq/califit-be/goa/design
// --out=$(GOPATH)/src/github.com/hieuphq/califit-be/goa
// --version=v1.4.0

package app

import (
	"fmt"
	"strings"
)

// CenterHref returns the resource href.
func CenterHref(centerID interface{}) string {
	paramcenterID := strings.TrimLeftFunc(fmt.Sprintf("%v", centerID), func(r rune) bool { return r == '/' })
	return fmt.Sprintf("/api/center/%v", paramcenterID)
}

// CityHref returns the resource href.
func CityHref(cityID interface{}) string {
	paramcityID := strings.TrimLeftFunc(fmt.Sprintf("%v", cityID), func(r rune) bool { return r == '/' })
	return fmt.Sprintf("/api/city/%v", paramcityID)
}
