// Code generated by SQLBoiler (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

var TableNames = struct {
	Address        string
	Category       string
	Center         string
	City           string
	Class          string
	Image          string
	ImageMap       string
	Permission     string
	Role           string
	RolePermission string
	Schedule       string
	ScheduleDetail string
	Tag            string
	TagMap         string
	Trainer        string
	User           string
	UserRole       string
	UserSession    string
}{
	Address:        "address",
	Category:       "category",
	Center:         "center",
	City:           "city",
	Class:          "class",
	Image:          "image",
	ImageMap:       "image_map",
	Permission:     "permission",
	Role:           "role",
	RolePermission: "role_permission",
	Schedule:       "schedule",
	ScheduleDetail: "schedule_detail",
	Tag:            "tag",
	TagMap:         "tag_map",
	Trainer:        "trainer",
	User:           "user",
	UserRole:       "user_role",
	UserSession:    "user_session",
}
