// Code generated by SQLBoiler (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import "testing"

func TestUpsert(t *testing.T) {
	t.Run("Addresses", testAddressesUpsert)

	t.Run("Categories", testCategoriesUpsert)

	t.Run("Centers", testCentersUpsert)

	t.Run("Cities", testCitiesUpsert)

	t.Run("Classes", testClassesUpsert)

	t.Run("Images", testImagesUpsert)

	t.Run("ImageMaps", testImageMapsUpsert)

	t.Run("Permissions", testPermissionsUpsert)

	t.Run("Roles", testRolesUpsert)

	t.Run("RolePermissions", testRolePermissionsUpsert)

	t.Run("Schedules", testSchedulesUpsert)

	t.Run("ScheduleDetails", testScheduleDetailsUpsert)

	t.Run("Tags", testTagsUpsert)

	t.Run("TagMaps", testTagMapsUpsert)

	t.Run("Trainers", testTrainersUpsert)

	t.Run("Users", testUsersUpsert)

	t.Run("UserRoles", testUserRolesUpsert)

	t.Run("UserSessions", testUserSessionsUpsert)
}
