// Code generated by SQLBoiler (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"context"
	"database/sql"
	"fmt"
	"reflect"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/pkg/errors"
	"github.com/volatiletech/null"
	"github.com/volatiletech/sqlboiler/boil"
	"github.com/volatiletech/sqlboiler/queries"
	"github.com/volatiletech/sqlboiler/queries/qm"
	"github.com/volatiletech/sqlboiler/strmangle"
)

// Trainer is an object representing the database table.
type Trainer struct {
	ID        string      `boil:"id" json:"id" toml:"id" yaml:"id"`
	Name      null.String `boil:"name" json:"name,omitempty" toml:"name" yaml:"name,omitempty"`
	ImageID   null.String `boil:"image_id" json:"image_id,omitempty" toml:"image_id" yaml:"image_id,omitempty"`
	CreatedAt time.Time   `boil:"created_at" json:"created_at" toml:"created_at" yaml:"created_at"`
	UpdatedAt time.Time   `boil:"updated_at" json:"updated_at" toml:"updated_at" yaml:"updated_at"`

	R *trainerR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L trainerL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

var TrainerColumns = struct {
	ID        string
	Name      string
	ImageID   string
	CreatedAt string
	UpdatedAt string
}{
	ID:        "id",
	Name:      "name",
	ImageID:   "image_id",
	CreatedAt: "created_at",
	UpdatedAt: "updated_at",
}

// TrainerRels is where relationship names are stored.
var TrainerRels = struct {
	Image           string
	ScheduleDetails string
}{
	Image:           "Image",
	ScheduleDetails: "ScheduleDetails",
}

// trainerR is where relationships are stored.
type trainerR struct {
	Image           *Image
	ScheduleDetails ScheduleDetailSlice
}

// NewStruct creates a new relationship struct
func (*trainerR) NewStruct() *trainerR {
	return &trainerR{}
}

// trainerL is where Load methods for each relationship are stored.
type trainerL struct{}

var (
	trainerColumns               = []string{"id", "name", "image_id", "created_at", "updated_at"}
	trainerColumnsWithoutDefault = []string{"id", "name", "image_id"}
	trainerColumnsWithDefault    = []string{"created_at", "updated_at"}
	trainerPrimaryKeyColumns     = []string{"id"}
)

type (
	// TrainerSlice is an alias for a slice of pointers to Trainer.
	// This should generally be used opposed to []Trainer.
	TrainerSlice []*Trainer
	// TrainerHook is the signature for custom Trainer hook methods
	TrainerHook func(context.Context, boil.ContextExecutor, *Trainer) error

	trainerQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	trainerType                 = reflect.TypeOf(&Trainer{})
	trainerMapping              = queries.MakeStructMapping(trainerType)
	trainerPrimaryKeyMapping, _ = queries.BindMapping(trainerType, trainerMapping, trainerPrimaryKeyColumns)
	trainerInsertCacheMut       sync.RWMutex
	trainerInsertCache          = make(map[string]insertCache)
	trainerUpdateCacheMut       sync.RWMutex
	trainerUpdateCache          = make(map[string]updateCache)
	trainerUpsertCacheMut       sync.RWMutex
	trainerUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
)

var trainerBeforeInsertHooks []TrainerHook
var trainerBeforeUpdateHooks []TrainerHook
var trainerBeforeDeleteHooks []TrainerHook
var trainerBeforeUpsertHooks []TrainerHook

var trainerAfterInsertHooks []TrainerHook
var trainerAfterSelectHooks []TrainerHook
var trainerAfterUpdateHooks []TrainerHook
var trainerAfterDeleteHooks []TrainerHook
var trainerAfterUpsertHooks []TrainerHook

// doBeforeInsertHooks executes all "before insert" hooks.
func (o *Trainer) doBeforeInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	for _, hook := range trainerBeforeInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpdateHooks executes all "before Update" hooks.
func (o *Trainer) doBeforeUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	for _, hook := range trainerBeforeUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeDeleteHooks executes all "before Delete" hooks.
func (o *Trainer) doBeforeDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	for _, hook := range trainerBeforeDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpsertHooks executes all "before Upsert" hooks.
func (o *Trainer) doBeforeUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	for _, hook := range trainerBeforeUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterInsertHooks executes all "after Insert" hooks.
func (o *Trainer) doAfterInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	for _, hook := range trainerAfterInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterSelectHooks executes all "after Select" hooks.
func (o *Trainer) doAfterSelectHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	for _, hook := range trainerAfterSelectHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpdateHooks executes all "after Update" hooks.
func (o *Trainer) doAfterUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	for _, hook := range trainerAfterUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterDeleteHooks executes all "after Delete" hooks.
func (o *Trainer) doAfterDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	for _, hook := range trainerAfterDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpsertHooks executes all "after Upsert" hooks.
func (o *Trainer) doAfterUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	for _, hook := range trainerAfterUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// AddTrainerHook registers your hook function for all future operations.
func AddTrainerHook(hookPoint boil.HookPoint, trainerHook TrainerHook) {
	switch hookPoint {
	case boil.BeforeInsertHook:
		trainerBeforeInsertHooks = append(trainerBeforeInsertHooks, trainerHook)
	case boil.BeforeUpdateHook:
		trainerBeforeUpdateHooks = append(trainerBeforeUpdateHooks, trainerHook)
	case boil.BeforeDeleteHook:
		trainerBeforeDeleteHooks = append(trainerBeforeDeleteHooks, trainerHook)
	case boil.BeforeUpsertHook:
		trainerBeforeUpsertHooks = append(trainerBeforeUpsertHooks, trainerHook)
	case boil.AfterInsertHook:
		trainerAfterInsertHooks = append(trainerAfterInsertHooks, trainerHook)
	case boil.AfterSelectHook:
		trainerAfterSelectHooks = append(trainerAfterSelectHooks, trainerHook)
	case boil.AfterUpdateHook:
		trainerAfterUpdateHooks = append(trainerAfterUpdateHooks, trainerHook)
	case boil.AfterDeleteHook:
		trainerAfterDeleteHooks = append(trainerAfterDeleteHooks, trainerHook)
	case boil.AfterUpsertHook:
		trainerAfterUpsertHooks = append(trainerAfterUpsertHooks, trainerHook)
	}
}

// One returns a single trainer record from the query.
func (q trainerQuery) One(ctx context.Context, exec boil.ContextExecutor) (*Trainer, error) {
	o := &Trainer{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(ctx, exec, o)
	if err != nil {
		if errors.Cause(err) == sql.ErrNoRows {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: failed to execute a one query for trainer")
	}

	if err := o.doAfterSelectHooks(ctx, exec); err != nil {
		return o, err
	}

	return o, nil
}

// All returns all Trainer records from the query.
func (q trainerQuery) All(ctx context.Context, exec boil.ContextExecutor) (TrainerSlice, error) {
	var o []*Trainer

	err := q.Bind(ctx, exec, &o)
	if err != nil {
		return nil, errors.Wrap(err, "models: failed to assign all query results to Trainer slice")
	}

	if len(trainerAfterSelectHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterSelectHooks(ctx, exec); err != nil {
				return o, err
			}
		}
	}

	return o, nil
}

// Count returns the count of all Trainer records in the query.
func (q trainerQuery) Count(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to count trainer rows")
	}

	return count, nil
}

// Exists checks if the row exists in the table.
func (q trainerQuery) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "models: failed to check if trainer exists")
	}

	return count > 0, nil
}

// Image pointed to by the foreign key.
func (o *Trainer) Image(mods ...qm.QueryMod) imageQuery {
	queryMods := []qm.QueryMod{
		qm.Where("id=?", o.ImageID),
	}

	queryMods = append(queryMods, mods...)

	query := Images(queryMods...)
	queries.SetFrom(query.Query, "\"image\"")

	return query
}

// ScheduleDetails retrieves all the schedule_detail's ScheduleDetails with an executor.
func (o *Trainer) ScheduleDetails(mods ...qm.QueryMod) scheduleDetailQuery {
	var queryMods []qm.QueryMod
	if len(mods) != 0 {
		queryMods = append(queryMods, mods...)
	}

	queryMods = append(queryMods,
		qm.Where("\"schedule_detail\".\"trainer_id\"=?", o.ID),
	)

	query := ScheduleDetails(queryMods...)
	queries.SetFrom(query.Query, "\"schedule_detail\"")

	if len(queries.GetSelect(query.Query)) == 0 {
		queries.SetSelect(query.Query, []string{"\"schedule_detail\".*"})
	}

	return query
}

// LoadImage allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for an N-1 relationship.
func (trainerL) LoadImage(ctx context.Context, e boil.ContextExecutor, singular bool, maybeTrainer interface{}, mods queries.Applicator) error {
	var slice []*Trainer
	var object *Trainer

	if singular {
		object = maybeTrainer.(*Trainer)
	} else {
		slice = *maybeTrainer.(*[]*Trainer)
	}

	args := make([]interface{}, 0, 1)
	if singular {
		if object.R == nil {
			object.R = &trainerR{}
		}
		if !queries.IsNil(object.ImageID) {
			args = append(args, object.ImageID)
		}

	} else {
	Outer:
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &trainerR{}
			}

			for _, a := range args {
				if queries.Equal(a, obj.ImageID) {
					continue Outer
				}
			}

			if !queries.IsNil(obj.ImageID) {
				args = append(args, obj.ImageID)
			}

		}
	}

	query := NewQuery(qm.From(`image`), qm.WhereIn(`id in ?`, args...))
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load Image")
	}

	var resultSlice []*Image
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice Image")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results of eager load for image")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for image")
	}

	if len(trainerAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(ctx, e); err != nil {
				return err
			}
		}
	}

	if len(resultSlice) == 0 {
		return nil
	}

	if singular {
		foreign := resultSlice[0]
		object.R.Image = foreign
		if foreign.R == nil {
			foreign.R = &imageR{}
		}
		foreign.R.Trainers = append(foreign.R.Trainers, object)
		return nil
	}

	for _, local := range slice {
		for _, foreign := range resultSlice {
			if queries.Equal(local.ImageID, foreign.ID) {
				local.R.Image = foreign
				if foreign.R == nil {
					foreign.R = &imageR{}
				}
				foreign.R.Trainers = append(foreign.R.Trainers, local)
				break
			}
		}
	}

	return nil
}

// LoadScheduleDetails allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for a 1-M or N-M relationship.
func (trainerL) LoadScheduleDetails(ctx context.Context, e boil.ContextExecutor, singular bool, maybeTrainer interface{}, mods queries.Applicator) error {
	var slice []*Trainer
	var object *Trainer

	if singular {
		object = maybeTrainer.(*Trainer)
	} else {
		slice = *maybeTrainer.(*[]*Trainer)
	}

	args := make([]interface{}, 0, 1)
	if singular {
		if object.R == nil {
			object.R = &trainerR{}
		}
		args = append(args, object.ID)
	} else {
	Outer:
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &trainerR{}
			}

			for _, a := range args {
				if queries.Equal(a, obj.ID) {
					continue Outer
				}
			}

			args = append(args, obj.ID)
		}
	}

	query := NewQuery(qm.From(`schedule_detail`), qm.WhereIn(`trainer_id in ?`, args...))
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load schedule_detail")
	}

	var resultSlice []*ScheduleDetail
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice schedule_detail")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results in eager load on schedule_detail")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for schedule_detail")
	}

	if len(scheduleDetailAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(ctx, e); err != nil {
				return err
			}
		}
	}
	if singular {
		object.R.ScheduleDetails = resultSlice
		for _, foreign := range resultSlice {
			if foreign.R == nil {
				foreign.R = &scheduleDetailR{}
			}
			foreign.R.Trainer = object
		}
		return nil
	}

	for _, foreign := range resultSlice {
		for _, local := range slice {
			if queries.Equal(local.ID, foreign.TrainerID) {
				local.R.ScheduleDetails = append(local.R.ScheduleDetails, foreign)
				if foreign.R == nil {
					foreign.R = &scheduleDetailR{}
				}
				foreign.R.Trainer = local
				break
			}
		}
	}

	return nil
}

// SetImage of the trainer to the related item.
// Sets o.R.Image to related.
// Adds o to related.R.Trainers.
func (o *Trainer) SetImage(ctx context.Context, exec boil.ContextExecutor, insert bool, related *Image) error {
	var err error
	if insert {
		if err = related.Insert(ctx, exec, boil.Infer()); err != nil {
			return errors.Wrap(err, "failed to insert into foreign table")
		}
	}

	updateQuery := fmt.Sprintf(
		"UPDATE \"trainer\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, []string{"image_id"}),
		strmangle.WhereClause("\"", "\"", 2, trainerPrimaryKeyColumns),
	)
	values := []interface{}{related.ID, o.ID}

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, updateQuery)
		fmt.Fprintln(boil.DebugWriter, values)
	}

	if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	queries.Assign(&o.ImageID, related.ID)
	if o.R == nil {
		o.R = &trainerR{
			Image: related,
		}
	} else {
		o.R.Image = related
	}

	if related.R == nil {
		related.R = &imageR{
			Trainers: TrainerSlice{o},
		}
	} else {
		related.R.Trainers = append(related.R.Trainers, o)
	}

	return nil
}

// RemoveImage relationship.
// Sets o.R.Image to nil.
// Removes o from all passed in related items' relationships struct (Optional).
func (o *Trainer) RemoveImage(ctx context.Context, exec boil.ContextExecutor, related *Image) error {
	var err error

	queries.SetScanner(&o.ImageID, nil)
	if _, err = o.Update(ctx, exec, boil.Whitelist("image_id")); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	o.R.Image = nil
	if related == nil || related.R == nil {
		return nil
	}

	for i, ri := range related.R.Trainers {
		if queries.Equal(o.ImageID, ri.ImageID) {
			continue
		}

		ln := len(related.R.Trainers)
		if ln > 1 && i < ln-1 {
			related.R.Trainers[i] = related.R.Trainers[ln-1]
		}
		related.R.Trainers = related.R.Trainers[:ln-1]
		break
	}
	return nil
}

// AddScheduleDetails adds the given related objects to the existing relationships
// of the trainer, optionally inserting them as new records.
// Appends related to o.R.ScheduleDetails.
// Sets related.R.Trainer appropriately.
func (o *Trainer) AddScheduleDetails(ctx context.Context, exec boil.ContextExecutor, insert bool, related ...*ScheduleDetail) error {
	var err error
	for _, rel := range related {
		if insert {
			queries.Assign(&rel.TrainerID, o.ID)
			if err = rel.Insert(ctx, exec, boil.Infer()); err != nil {
				return errors.Wrap(err, "failed to insert into foreign table")
			}
		} else {
			updateQuery := fmt.Sprintf(
				"UPDATE \"schedule_detail\" SET %s WHERE %s",
				strmangle.SetParamNames("\"", "\"", 1, []string{"trainer_id"}),
				strmangle.WhereClause("\"", "\"", 2, scheduleDetailPrimaryKeyColumns),
			)
			values := []interface{}{o.ID, rel.ID}

			if boil.DebugMode {
				fmt.Fprintln(boil.DebugWriter, updateQuery)
				fmt.Fprintln(boil.DebugWriter, values)
			}

			if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
				return errors.Wrap(err, "failed to update foreign table")
			}

			queries.Assign(&rel.TrainerID, o.ID)
		}
	}

	if o.R == nil {
		o.R = &trainerR{
			ScheduleDetails: related,
		}
	} else {
		o.R.ScheduleDetails = append(o.R.ScheduleDetails, related...)
	}

	for _, rel := range related {
		if rel.R == nil {
			rel.R = &scheduleDetailR{
				Trainer: o,
			}
		} else {
			rel.R.Trainer = o
		}
	}
	return nil
}

// SetScheduleDetails removes all previously related items of the
// trainer replacing them completely with the passed
// in related items, optionally inserting them as new records.
// Sets o.R.Trainer's ScheduleDetails accordingly.
// Replaces o.R.ScheduleDetails with related.
// Sets related.R.Trainer's ScheduleDetails accordingly.
func (o *Trainer) SetScheduleDetails(ctx context.Context, exec boil.ContextExecutor, insert bool, related ...*ScheduleDetail) error {
	query := "update \"schedule_detail\" set \"trainer_id\" = null where \"trainer_id\" = $1"
	values := []interface{}{o.ID}
	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, query)
		fmt.Fprintln(boil.DebugWriter, values)
	}

	_, err := exec.ExecContext(ctx, query, values...)
	if err != nil {
		return errors.Wrap(err, "failed to remove relationships before set")
	}

	if o.R != nil {
		for _, rel := range o.R.ScheduleDetails {
			queries.SetScanner(&rel.TrainerID, nil)
			if rel.R == nil {
				continue
			}

			rel.R.Trainer = nil
		}

		o.R.ScheduleDetails = nil
	}
	return o.AddScheduleDetails(ctx, exec, insert, related...)
}

// RemoveScheduleDetails relationships from objects passed in.
// Removes related items from R.ScheduleDetails (uses pointer comparison, removal does not keep order)
// Sets related.R.Trainer.
func (o *Trainer) RemoveScheduleDetails(ctx context.Context, exec boil.ContextExecutor, related ...*ScheduleDetail) error {
	var err error
	for _, rel := range related {
		queries.SetScanner(&rel.TrainerID, nil)
		if rel.R != nil {
			rel.R.Trainer = nil
		}
		if _, err = rel.Update(ctx, exec, boil.Whitelist("trainer_id")); err != nil {
			return err
		}
	}
	if o.R == nil {
		return nil
	}

	for _, rel := range related {
		for i, ri := range o.R.ScheduleDetails {
			if rel != ri {
				continue
			}

			ln := len(o.R.ScheduleDetails)
			if ln > 1 && i < ln-1 {
				o.R.ScheduleDetails[i] = o.R.ScheduleDetails[ln-1]
			}
			o.R.ScheduleDetails = o.R.ScheduleDetails[:ln-1]
			break
		}
	}

	return nil
}

// Trainers retrieves all the records using an executor.
func Trainers(mods ...qm.QueryMod) trainerQuery {
	mods = append(mods, qm.From("\"trainer\""))
	return trainerQuery{NewQuery(mods...)}
}

// FindTrainer retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindTrainer(ctx context.Context, exec boil.ContextExecutor, iD string, selectCols ...string) (*Trainer, error) {
	trainerObj := &Trainer{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from \"trainer\" where \"id\"=$1", sel,
	)

	q := queries.Raw(query, iD)

	err := q.Bind(ctx, exec, trainerObj)
	if err != nil {
		if errors.Cause(err) == sql.ErrNoRows {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: unable to select from trainer")
	}

	return trainerObj, nil
}

// Insert a single record using an executor.
// See boil.Columns.InsertColumnSet documentation to understand column list inference for inserts.
func (o *Trainer) Insert(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) error {
	if o == nil {
		return errors.New("models: no trainer provided for insertion")
	}

	var err error
	currTime := time.Now().In(boil.GetLocation())

	if o.CreatedAt.IsZero() {
		o.CreatedAt = currTime
	}
	if o.UpdatedAt.IsZero() {
		o.UpdatedAt = currTime
	}

	if err := o.doBeforeInsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(trainerColumnsWithDefault, o)

	key := makeCacheKey(columns, nzDefaults)
	trainerInsertCacheMut.RLock()
	cache, cached := trainerInsertCache[key]
	trainerInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := columns.InsertColumnSet(
			trainerColumns,
			trainerColumnsWithDefault,
			trainerColumnsWithoutDefault,
			nzDefaults,
		)

		cache.valueMapping, err = queries.BindMapping(trainerType, trainerMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(trainerType, trainerMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO \"trainer\" (\"%s\") %%sVALUES (%s)%%s", strings.Join(wl, "\",\""), strmangle.Placeholders(dialect.UseIndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO \"trainer\" %sDEFAULT VALUES%s"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			queryReturning = fmt.Sprintf(" RETURNING \"%s\"", strings.Join(returnColumns, "\",\""))
		}

		cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, cache.query)
		fmt.Fprintln(boil.DebugWriter, vals)
	}

	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}

	if err != nil {
		return errors.Wrap(err, "models: unable to insert into trainer")
	}

	if !cached {
		trainerInsertCacheMut.Lock()
		trainerInsertCache[key] = cache
		trainerInsertCacheMut.Unlock()
	}

	return o.doAfterInsertHooks(ctx, exec)
}

// Update uses an executor to update the Trainer.
// See boil.Columns.UpdateColumnSet documentation to understand column list inference for updates.
// Update does not automatically update the record in case of default values. Use .Reload() to refresh the records.
func (o *Trainer) Update(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) (int64, error) {
	currTime := time.Now().In(boil.GetLocation())

	o.UpdatedAt = currTime

	var err error
	if err = o.doBeforeUpdateHooks(ctx, exec); err != nil {
		return 0, err
	}
	key := makeCacheKey(columns, nil)
	trainerUpdateCacheMut.RLock()
	cache, cached := trainerUpdateCache[key]
	trainerUpdateCacheMut.RUnlock()

	if !cached {
		wl := columns.UpdateColumnSet(
			trainerColumns,
			trainerPrimaryKeyColumns,
		)

		if !columns.IsWhitelist() {
			wl = strmangle.SetComplement(wl, []string{"created_at"})
		}
		if len(wl) == 0 {
			return 0, errors.New("models: unable to update trainer, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE \"trainer\" SET %s WHERE %s",
			strmangle.SetParamNames("\"", "\"", 1, wl),
			strmangle.WhereClause("\"", "\"", len(wl)+1, trainerPrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(trainerType, trainerMapping, append(wl, trainerPrimaryKeyColumns...))
		if err != nil {
			return 0, err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, cache.query)
		fmt.Fprintln(boil.DebugWriter, values)
	}

	var result sql.Result
	result, err = exec.ExecContext(ctx, cache.query, values...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update trainer row")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by update for trainer")
	}

	if !cached {
		trainerUpdateCacheMut.Lock()
		trainerUpdateCache[key] = cache
		trainerUpdateCacheMut.Unlock()
	}

	return rowsAff, o.doAfterUpdateHooks(ctx, exec)
}

// UpdateAll updates all rows with the specified column values.
func (q trainerQuery) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	queries.SetUpdate(q.Query, cols)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all for trainer")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected for trainer")
	}

	return rowsAff, nil
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o TrainerSlice) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	ln := int64(len(o))
	if ln == 0 {
		return 0, nil
	}

	if len(cols) == 0 {
		return 0, errors.New("models: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]interface{}, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), trainerPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE \"trainer\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), len(colNames)+1, trainerPrimaryKeyColumns, len(o)))

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, sql)
		fmt.Fprintln(boil.DebugWriter, args...)
	}

	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all in trainer slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected all in update all trainer")
	}
	return rowsAff, nil
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
// See boil.Columns documentation for how to properly use updateColumns and insertColumns.
func (o *Trainer) Upsert(ctx context.Context, exec boil.ContextExecutor, updateOnConflict bool, conflictColumns []string, updateColumns, insertColumns boil.Columns) error {
	if o == nil {
		return errors.New("models: no trainer provided for upsert")
	}
	currTime := time.Now().In(boil.GetLocation())

	if o.CreatedAt.IsZero() {
		o.CreatedAt = currTime
	}
	o.UpdatedAt = currTime

	if err := o.doBeforeUpsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(trainerColumnsWithDefault, o)

	// Build cache key in-line uglily - mysql vs psql problems
	buf := strmangle.GetBuffer()
	if updateOnConflict {
		buf.WriteByte('t')
	} else {
		buf.WriteByte('f')
	}
	buf.WriteByte('.')
	for _, c := range conflictColumns {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(updateColumns.Kind))
	for _, c := range updateColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(insertColumns.Kind))
	for _, c := range insertColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	trainerUpsertCacheMut.RLock()
	cache, cached := trainerUpsertCache[key]
	trainerUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, ret := insertColumns.InsertColumnSet(
			trainerColumns,
			trainerColumnsWithDefault,
			trainerColumnsWithoutDefault,
			nzDefaults,
		)
		update := updateColumns.UpdateColumnSet(
			trainerColumns,
			trainerPrimaryKeyColumns,
		)

		if len(update) == 0 {
			return errors.New("models: unable to upsert trainer, could not build update column list")
		}

		conflict := conflictColumns
		if len(conflict) == 0 {
			conflict = make([]string, len(trainerPrimaryKeyColumns))
			copy(conflict, trainerPrimaryKeyColumns)
		}
		cache.query = buildUpsertQueryPostgres(dialect, "\"trainer\"", updateOnConflict, ret, update, conflict, insert)

		cache.valueMapping, err = queries.BindMapping(trainerType, trainerMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(trainerType, trainerMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []interface{}
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, cache.query)
		fmt.Fprintln(boil.DebugWriter, vals)
	}

	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(returns...)
		if err == sql.ErrNoRows {
			err = nil // Postgres doesn't return anything when there's no update
		}
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}
	if err != nil {
		return errors.Wrap(err, "models: unable to upsert trainer")
	}

	if !cached {
		trainerUpsertCacheMut.Lock()
		trainerUpsertCache[key] = cache
		trainerUpsertCacheMut.Unlock()
	}

	return o.doAfterUpsertHooks(ctx, exec)
}

// Delete deletes a single Trainer record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *Trainer) Delete(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if o == nil {
		return 0, errors.New("models: no Trainer provided for delete")
	}

	if err := o.doBeforeDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), trainerPrimaryKeyMapping)
	sql := "DELETE FROM \"trainer\" WHERE \"id\"=$1"

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, sql)
		fmt.Fprintln(boil.DebugWriter, args...)
	}

	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete from trainer")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by delete for trainer")
	}

	if err := o.doAfterDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	return rowsAff, nil
}

// DeleteAll deletes all matching rows.
func (q trainerQuery) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if q.Query == nil {
		return 0, errors.New("models: no trainerQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from trainer")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for trainer")
	}

	return rowsAff, nil
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o TrainerSlice) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if o == nil {
		return 0, errors.New("models: no Trainer slice provided for delete all")
	}

	if len(o) == 0 {
		return 0, nil
	}

	if len(trainerBeforeDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doBeforeDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	var args []interface{}
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), trainerPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM \"trainer\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, trainerPrimaryKeyColumns, len(o))

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, sql)
		fmt.Fprintln(boil.DebugWriter, args)
	}

	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from trainer slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for trainer")
	}

	if len(trainerAfterDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	return rowsAff, nil
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *Trainer) Reload(ctx context.Context, exec boil.ContextExecutor) error {
	ret, err := FindTrainer(ctx, exec, o.ID)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *TrainerSlice) ReloadAll(ctx context.Context, exec boil.ContextExecutor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	slice := TrainerSlice{}
	var args []interface{}
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), trainerPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT \"trainer\".* FROM \"trainer\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, trainerPrimaryKeyColumns, len(*o))

	q := queries.Raw(sql, args...)

	err := q.Bind(ctx, exec, &slice)
	if err != nil {
		return errors.Wrap(err, "models: unable to reload all in TrainerSlice")
	}

	*o = slice

	return nil
}

// TrainerExists checks if the Trainer row exists.
func TrainerExists(ctx context.Context, exec boil.ContextExecutor, iD string) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from \"trainer\" where \"id\"=$1 limit 1)"

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, sql)
		fmt.Fprintln(boil.DebugWriter, iD)
	}

	row := exec.QueryRowContext(ctx, sql, iD)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "models: unable to check if trainer exists")
	}

	return exists, nil
}
