// Code generated by SQLBoiler (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"bytes"
	"context"
	"reflect"
	"testing"

	"github.com/volatiletech/sqlboiler/boil"
	"github.com/volatiletech/sqlboiler/queries"
	"github.com/volatiletech/sqlboiler/randomize"
	"github.com/volatiletech/sqlboiler/strmangle"
)

var (
	// Relationships sometimes use the reflection helper queries.Equal/queries.Assign
	// so force a package dependency in case they don't.
	_ = queries.Equal
)

func testUserSessions(t *testing.T) {
	t.Parallel()

	query := UserSessions()

	if query.Query == nil {
		t.Error("expected a query, got nothing")
	}
}

func testUserSessionsDelete(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &UserSession{}
	if err = randomize.Struct(seed, o, userSessionDBTypes, true, userSessionColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize UserSession struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := o.Delete(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := UserSessions().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testUserSessionsQueryDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &UserSession{}
	if err = randomize.Struct(seed, o, userSessionDBTypes, true, userSessionColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize UserSession struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := UserSessions().DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := UserSessions().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testUserSessionsSliceDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &UserSession{}
	if err = randomize.Struct(seed, o, userSessionDBTypes, true, userSessionColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize UserSession struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := UserSessionSlice{o}

	if rowsAff, err := slice.DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := UserSessions().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testUserSessionsExists(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &UserSession{}
	if err = randomize.Struct(seed, o, userSessionDBTypes, true, userSessionColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize UserSession struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	e, err := UserSessionExists(ctx, tx, o.ID)
	if err != nil {
		t.Errorf("Unable to check if UserSession exists: %s", err)
	}
	if !e {
		t.Errorf("Expected UserSessionExists to return true, but got false.")
	}
}

func testUserSessionsFind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &UserSession{}
	if err = randomize.Struct(seed, o, userSessionDBTypes, true, userSessionColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize UserSession struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	userSessionFound, err := FindUserSession(ctx, tx, o.ID)
	if err != nil {
		t.Error(err)
	}

	if userSessionFound == nil {
		t.Error("want a record, got nil")
	}
}

func testUserSessionsBind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &UserSession{}
	if err = randomize.Struct(seed, o, userSessionDBTypes, true, userSessionColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize UserSession struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = UserSessions().Bind(ctx, tx, o); err != nil {
		t.Error(err)
	}
}

func testUserSessionsOne(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &UserSession{}
	if err = randomize.Struct(seed, o, userSessionDBTypes, true, userSessionColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize UserSession struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if x, err := UserSessions().One(ctx, tx); err != nil {
		t.Error(err)
	} else if x == nil {
		t.Error("expected to get a non nil record")
	}
}

func testUserSessionsAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	userSessionOne := &UserSession{}
	userSessionTwo := &UserSession{}
	if err = randomize.Struct(seed, userSessionOne, userSessionDBTypes, false, userSessionColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize UserSession struct: %s", err)
	}
	if err = randomize.Struct(seed, userSessionTwo, userSessionDBTypes, false, userSessionColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize UserSession struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = userSessionOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = userSessionTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := UserSessions().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 2 {
		t.Error("want 2 records, got:", len(slice))
	}
}

func testUserSessionsCount(t *testing.T) {
	t.Parallel()

	var err error
	seed := randomize.NewSeed()
	userSessionOne := &UserSession{}
	userSessionTwo := &UserSession{}
	if err = randomize.Struct(seed, userSessionOne, userSessionDBTypes, false, userSessionColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize UserSession struct: %s", err)
	}
	if err = randomize.Struct(seed, userSessionTwo, userSessionDBTypes, false, userSessionColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize UserSession struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = userSessionOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = userSessionTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := UserSessions().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 2 {
		t.Error("want 2 records, got:", count)
	}
}

func userSessionBeforeInsertHook(ctx context.Context, e boil.ContextExecutor, o *UserSession) error {
	*o = UserSession{}
	return nil
}

func userSessionAfterInsertHook(ctx context.Context, e boil.ContextExecutor, o *UserSession) error {
	*o = UserSession{}
	return nil
}

func userSessionAfterSelectHook(ctx context.Context, e boil.ContextExecutor, o *UserSession) error {
	*o = UserSession{}
	return nil
}

func userSessionBeforeUpdateHook(ctx context.Context, e boil.ContextExecutor, o *UserSession) error {
	*o = UserSession{}
	return nil
}

func userSessionAfterUpdateHook(ctx context.Context, e boil.ContextExecutor, o *UserSession) error {
	*o = UserSession{}
	return nil
}

func userSessionBeforeDeleteHook(ctx context.Context, e boil.ContextExecutor, o *UserSession) error {
	*o = UserSession{}
	return nil
}

func userSessionAfterDeleteHook(ctx context.Context, e boil.ContextExecutor, o *UserSession) error {
	*o = UserSession{}
	return nil
}

func userSessionBeforeUpsertHook(ctx context.Context, e boil.ContextExecutor, o *UserSession) error {
	*o = UserSession{}
	return nil
}

func userSessionAfterUpsertHook(ctx context.Context, e boil.ContextExecutor, o *UserSession) error {
	*o = UserSession{}
	return nil
}

func testUserSessionsHooks(t *testing.T) {
	t.Parallel()

	var err error

	ctx := context.Background()
	empty := &UserSession{}
	o := &UserSession{}

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, o, userSessionDBTypes, false); err != nil {
		t.Errorf("Unable to randomize UserSession object: %s", err)
	}

	AddUserSessionHook(boil.BeforeInsertHook, userSessionBeforeInsertHook)
	if err = o.doBeforeInsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeInsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeInsertHook function to empty object, but got: %#v", o)
	}
	userSessionBeforeInsertHooks = []UserSessionHook{}

	AddUserSessionHook(boil.AfterInsertHook, userSessionAfterInsertHook)
	if err = o.doAfterInsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterInsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterInsertHook function to empty object, but got: %#v", o)
	}
	userSessionAfterInsertHooks = []UserSessionHook{}

	AddUserSessionHook(boil.AfterSelectHook, userSessionAfterSelectHook)
	if err = o.doAfterSelectHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterSelectHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterSelectHook function to empty object, but got: %#v", o)
	}
	userSessionAfterSelectHooks = []UserSessionHook{}

	AddUserSessionHook(boil.BeforeUpdateHook, userSessionBeforeUpdateHook)
	if err = o.doBeforeUpdateHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeUpdateHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeUpdateHook function to empty object, but got: %#v", o)
	}
	userSessionBeforeUpdateHooks = []UserSessionHook{}

	AddUserSessionHook(boil.AfterUpdateHook, userSessionAfterUpdateHook)
	if err = o.doAfterUpdateHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterUpdateHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterUpdateHook function to empty object, but got: %#v", o)
	}
	userSessionAfterUpdateHooks = []UserSessionHook{}

	AddUserSessionHook(boil.BeforeDeleteHook, userSessionBeforeDeleteHook)
	if err = o.doBeforeDeleteHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeDeleteHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeDeleteHook function to empty object, but got: %#v", o)
	}
	userSessionBeforeDeleteHooks = []UserSessionHook{}

	AddUserSessionHook(boil.AfterDeleteHook, userSessionAfterDeleteHook)
	if err = o.doAfterDeleteHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterDeleteHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterDeleteHook function to empty object, but got: %#v", o)
	}
	userSessionAfterDeleteHooks = []UserSessionHook{}

	AddUserSessionHook(boil.BeforeUpsertHook, userSessionBeforeUpsertHook)
	if err = o.doBeforeUpsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeUpsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeUpsertHook function to empty object, but got: %#v", o)
	}
	userSessionBeforeUpsertHooks = []UserSessionHook{}

	AddUserSessionHook(boil.AfterUpsertHook, userSessionAfterUpsertHook)
	if err = o.doAfterUpsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterUpsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterUpsertHook function to empty object, but got: %#v", o)
	}
	userSessionAfterUpsertHooks = []UserSessionHook{}
}

func testUserSessionsInsert(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &UserSession{}
	if err = randomize.Struct(seed, o, userSessionDBTypes, true, userSessionColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize UserSession struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := UserSessions().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testUserSessionsInsertWhitelist(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &UserSession{}
	if err = randomize.Struct(seed, o, userSessionDBTypes, true); err != nil {
		t.Errorf("Unable to randomize UserSession struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Whitelist(userSessionColumnsWithoutDefault...)); err != nil {
		t.Error(err)
	}

	count, err := UserSessions().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testUserSessionToOneUserUsingUser(t *testing.T) {
	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var local UserSession
	var foreign User

	seed := randomize.NewSeed()
	if err := randomize.Struct(seed, &local, userSessionDBTypes, true, userSessionColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize UserSession struct: %s", err)
	}
	if err := randomize.Struct(seed, &foreign, userDBTypes, false, userColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize User struct: %s", err)
	}

	if err := foreign.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	queries.Assign(&local.UserID, foreign.ID)
	if err := local.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	check, err := local.User().One(ctx, tx)
	if err != nil {
		t.Fatal(err)
	}

	if !queries.Equal(check.ID, foreign.ID) {
		t.Errorf("want: %v, got %v", foreign.ID, check.ID)
	}

	slice := UserSessionSlice{&local}
	if err = local.L.LoadUser(ctx, tx, false, (*[]*UserSession)(&slice), nil); err != nil {
		t.Fatal(err)
	}
	if local.R.User == nil {
		t.Error("struct should have been eager loaded")
	}

	local.R.User = nil
	if err = local.L.LoadUser(ctx, tx, true, &local, nil); err != nil {
		t.Fatal(err)
	}
	if local.R.User == nil {
		t.Error("struct should have been eager loaded")
	}
}

func testUserSessionToOneSetOpUserUsingUser(t *testing.T) {
	var err error

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a UserSession
	var b, c User

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, userSessionDBTypes, false, strmangle.SetComplement(userSessionPrimaryKeyColumns, userSessionColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &b, userDBTypes, false, strmangle.SetComplement(userPrimaryKeyColumns, userColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &c, userDBTypes, false, strmangle.SetComplement(userPrimaryKeyColumns, userColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}

	if err := a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = b.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	for i, x := range []*User{&b, &c} {
		err = a.SetUser(ctx, tx, i != 0, x)
		if err != nil {
			t.Fatal(err)
		}

		if a.R.User != x {
			t.Error("relationship struct not set to correct value")
		}

		if x.R.UserSessions[0] != &a {
			t.Error("failed to append to foreign relationship struct")
		}
		if !queries.Equal(a.UserID, x.ID) {
			t.Error("foreign key was wrong value", a.UserID)
		}

		zero := reflect.Zero(reflect.TypeOf(a.UserID))
		reflect.Indirect(reflect.ValueOf(&a.UserID)).Set(zero)

		if err = a.Reload(ctx, tx); err != nil {
			t.Fatal("failed to reload", err)
		}

		if !queries.Equal(a.UserID, x.ID) {
			t.Error("foreign key was wrong value", a.UserID, x.ID)
		}
	}
}

func testUserSessionToOneRemoveOpUserUsingUser(t *testing.T) {
	var err error

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a UserSession
	var b User

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, userSessionDBTypes, false, strmangle.SetComplement(userSessionPrimaryKeyColumns, userSessionColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &b, userDBTypes, false, strmangle.SetComplement(userPrimaryKeyColumns, userColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}

	if err = a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	if err = a.SetUser(ctx, tx, true, &b); err != nil {
		t.Fatal(err)
	}

	if err = a.RemoveUser(ctx, tx, &b); err != nil {
		t.Error("failed to remove relationship")
	}

	count, err := a.User().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 0 {
		t.Error("want no relationships remaining")
	}

	if a.R.User != nil {
		t.Error("R struct entry should be nil")
	}

	if !queries.IsValuerNil(a.UserID) {
		t.Error("foreign key value should be nil")
	}

	if len(b.R.UserSessions) != 0 {
		t.Error("failed to remove a from b's relationships")
	}
}

func testUserSessionsReload(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &UserSession{}
	if err = randomize.Struct(seed, o, userSessionDBTypes, true, userSessionColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize UserSession struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = o.Reload(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testUserSessionsReloadAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &UserSession{}
	if err = randomize.Struct(seed, o, userSessionDBTypes, true, userSessionColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize UserSession struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := UserSessionSlice{o}

	if err = slice.ReloadAll(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testUserSessionsSelect(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &UserSession{}
	if err = randomize.Struct(seed, o, userSessionDBTypes, true, userSessionColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize UserSession struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := UserSessions().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 1 {
		t.Error("want one record, got:", len(slice))
	}
}

var (
	userSessionDBTypes = map[string]string{`CreatedAt`: `timestamp with time zone`, `ExpiredAt`: `timestamp with time zone`, `ID`: `uuid`, `Token`: `character varying`, `UpdatedAt`: `timestamp with time zone`, `UserID`: `uuid`}
	_                  = bytes.MinRead
)

func testUserSessionsUpdate(t *testing.T) {
	t.Parallel()

	if 0 == len(userSessionPrimaryKeyColumns) {
		t.Skip("Skipping table with no primary key columns")
	}
	if len(userSessionColumns) == len(userSessionPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &UserSession{}
	if err = randomize.Struct(seed, o, userSessionDBTypes, true, userSessionColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize UserSession struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := UserSessions().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, userSessionDBTypes, true, userSessionPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize UserSession struct: %s", err)
	}

	if rowsAff, err := o.Update(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only affect one row but affected", rowsAff)
	}
}

func testUserSessionsSliceUpdateAll(t *testing.T) {
	t.Parallel()

	if len(userSessionColumns) == len(userSessionPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &UserSession{}
	if err = randomize.Struct(seed, o, userSessionDBTypes, true, userSessionColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize UserSession struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := UserSessions().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, userSessionDBTypes, true, userSessionPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize UserSession struct: %s", err)
	}

	// Remove Primary keys and unique columns from what we plan to update
	var fields []string
	if strmangle.StringSliceMatch(userSessionColumns, userSessionPrimaryKeyColumns) {
		fields = userSessionColumns
	} else {
		fields = strmangle.SetComplement(
			userSessionColumns,
			userSessionPrimaryKeyColumns,
		)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	typ := reflect.TypeOf(o).Elem()
	n := typ.NumField()

	updateMap := M{}
	for _, col := range fields {
		for i := 0; i < n; i++ {
			f := typ.Field(i)
			if f.Tag.Get("boil") == col {
				updateMap[col] = value.Field(i).Interface()
			}
		}
	}

	slice := UserSessionSlice{o}
	if rowsAff, err := slice.UpdateAll(ctx, tx, updateMap); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("wanted one record updated but got", rowsAff)
	}
}

func testUserSessionsUpsert(t *testing.T) {
	t.Parallel()

	if len(userSessionColumns) == len(userSessionPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	// Attempt the INSERT side of an UPSERT
	o := UserSession{}
	if err = randomize.Struct(seed, &o, userSessionDBTypes, true); err != nil {
		t.Errorf("Unable to randomize UserSession struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Upsert(ctx, tx, false, nil, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert UserSession: %s", err)
	}

	count, err := UserSessions().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}

	// Attempt the UPDATE side of an UPSERT
	if err = randomize.Struct(seed, &o, userSessionDBTypes, false, userSessionPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize UserSession struct: %s", err)
	}

	if err = o.Upsert(ctx, tx, true, nil, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert UserSession: %s", err)
	}

	count, err = UserSessions().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}
}
